database = {
  dataSourceClassName = org.postgresql.ds.PGSimpleDataSource
  dataSource = {
    user = ccas
    password = ccas
    databaseName = ccas
    portNumber = 5432
    serverName = localhost
  }
  connectionTimeout = 30000
}

clubs = {
  tgbe = {
    clubUrlName = "the-great-british-empire"
    recruitment = {
      invitedExpiryDays = 180
      timeoutExpiryDays = 90
      checkedExpiryDays = 30
      minScoreRate = 0.375
      maxScoreRate = 0.875
      maxTimeoutRate = 0.125
      maxMatchTimeoutRate = 0.015625
      minMatchesFinished = 4
      minMatchesOngoing = 1
      maxGamesOngoing = 96
      maxClubs = 40
      maxHoursPerMove = 16
      maxHoursOffline = 48
      minElo = 1000
      maxElo = 2200
    }
  }
  devon = {
    clubUrlName = "devon-chess"
  }
  gents = {
    clubUrlName = "diagonally-challenged-gentlemens-club"
  }
}
