package ccas.cli

import ccas.cli.CompletionSpec.{Group, Leaf, PositionalKind}

/** Emits self-contained, pure-shell completion scripts (bash/zsh/fish) generated from [[CompletionSpec]]. The scripts
  * run entirely in the shell at `<TAB>` time — no JVM boot, no network — so completion is instant (the issue's <50ms
  * bar). The only JVM cost is running `ccas completion <shell>` once at install. Dynamic club-slug and job-id
  * candidates come from cache files written by normal `ccas` commands (see [[CompletionCache]]).
  *
  * Output is a pure function of [[CompletionSpec]] and is byte-stable (fixed iteration order), so `completions/ccas.bash`
  * can be the committed output of `bash` and `TestCcasCompletion` can assert the two match exactly.
  */
object CompletionEmitter {

  def render(shell: String): Either[String, String] = shell match {
    case "bash" => Right(bash)
    case "zsh"  => Right(zsh)
    case "fish" => Right(fish)
    case other  => Left(s"unknown shell '$other' (expected one of: bash, zsh, fish)")
  }

  // --- shared spec-derived fragments ---

  private def posTag(k: PositionalKind): String = k match {
    case PositionalKind.Slugs => "slugs"
    case PositionalKind.Slug  => "slug"
    case PositionalKind.JobId => "jobid"
    case PositionalKind.Shell => "shell"
    case _                    => ""
  }

  // `--help` is appended by the emitted scripts themselves, so it is dropped from the per-command option list here.
  private def optsOf(leaf: Leaf): String = leaf.flags.filterNot(_ == "--help").mkString(" ")

  /** `opts="…"; pos="…"` assignment fragment for a leaf (either half omitted when empty). */
  private def assigns(leaf: Leaf): String = {
    val opts = optsOf(leaf)
    val pos  = posTag(leaf.positional)
    List(
      Option.when(opts.nonEmpty)("opts=\"" + opts + "\""),
      Option.when(pos.nonEmpty)("pos=\"" + pos + "\"")
    ).flatten.mkString("; ")
  }

  private val top: String     = CompletionSpec.topLevel.mkString(" ")
  private val global: String  = CompletionSpec.globalFlags.mkString(" ")
  private val valueGuard: String = CompletionSpec.valueFlags.mkString("|")

  // Group commands consume two leading words (group + subcommand) before positionals, so their positional `base` is 2.
  // Derived from the group list so adding a group can't silently leave its subcommands' slug completion off-by-one.
  private val groupBaseGuard: String = CompletionSpec.groups.map(g => "$cmd == " + g.name).mkString(" || ")
  private val groupNames: String     = CompletionSpec.groups.map(_.name).mkString("/")

  // --- bash ---

  private def bashLeafArm(leaf: Leaf): String =
    "    " + leaf.name + ") " + assigns(leaf) + " ;;"

  private def bashGroupArm(group: Group): String = {
    val header = List(
      "    " + group.name + ")",
      "      case \"$sub\" in",
      "        \"\") COMPREPLY=( $(compgen -W \"" + group.children.mkString(" ") + " --help\" -- \"$cur\") ); return ;;"
    )
    val childArms = CompletionSpec.leavesOf(group.name).map(l => "        " + l.name + ") " + assigns(l) + " ;;")
    val footer = List("        *) COMPREPLY=(); return ;;", "      esac ;;")
    (header ++ childArms ++ footer).mkString("\n")
  }

  val bash: String = {
    val arms = CompletionSpec.topLevel.flatMap { name =>
      CompletionSpec.groups.find(_.name == name).map(bashGroupArm)
        .orElse(CompletionSpec.topLevelLeaves.find(_.name == name).map(bashLeafArm))
    }
    val lines = List(
      "# bash completion for ccas — generated, pure-shell (JVM-free, instant). See Sootopolis/ccas#49.",
      "#",
      "# DO NOT EDIT — generated by `ccas completion bash`.",
      "# Regenerate after a command-tree change:  ccas completion bash > completions/ccas.bash",
      "# TestCcasCompletion asserts this file equals the emitter output and stays valid bash.",
      "#",
      "# Install:  ln -sf \"$PWD/completions/ccas.bash\" ~/.local/share/bash-completion/completions/ccas",
      "# (bash-completion auto-loads it; or `source` it from ~/.bashrc).",
      "#",
      "# Club-slug and job-id completion read caches refreshed by normal ccas commands:",
      "#   ${XDG_CACHE_HOME:-$HOME/.cache}/ccas/clubs.txt        (one slug per line)",
      "#   ${XDG_CACHE_HOME:-$HOME/.cache}/ccas/recent-jobs.txt  (one job id per line)",
      "#",
      "# COMPREPLY=( $(compgen ...) ) is the standard, bash-3.2/macOS-safe completion idiom; the word-splitting is",
      "# intentional (compgen yields newline-separated, space-free candidates). mapfile is the SC2207 fix but is bash 4+.",
      "# shellcheck disable=SC2207",
      "",
      "_ccas_cache() {",
      "  local f=\"${XDG_CACHE_HOME:-$HOME/.cache}/ccas/$1\"",
      "  [[ -r $f ]] && cat -- \"$f\"",
      "}",
      "",
      "_ccas() {",
      "  local cur prev words cword",
      "  if declare -F _init_completion >/dev/null 2>&1; then",
      "    _init_completion -n : || return",
      "  else",
      "    cur=\"${COMP_WORDS[COMP_CWORD]}\"",
      "    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"",
      "    cword=$COMP_CWORD",
      "    words=(\"${COMP_WORDS[@]}\")",
      "  fi",
      "",
      "  local top=\"" + top + "\"",
      "  local global=\"" + global + "\"",
      "",
      "  # First non-flag word after \"ccas\" is the command; the next is the subcommand (" + groupNames + ").",
      "  local cmd=\"\" sub=\"\" i",
      "  for (( i = 1; i < cword; i++ )); do",
      "    case \"${words[i]}\" in",
      "      -*) ;;",
      "      *) if [[ -z $cmd ]]; then cmd=\"${words[i]}\"; else sub=\"${words[i]}\"; break; fi ;;",
      "    esac",
      "  done",
      "",
      "  # Right after a value-taking flag: let the user type the value, offer nothing.",
      "  case \"$prev\" in",
      "    " + valueGuard + ") return ;;",
      "  esac",
      "",
      "  local opts=\"\" pos=\"\"",
      "  case \"$cmd\" in",
      "    \"\") COMPREPLY=( $(compgen -W \"$top $global\" -- \"$cur\") ); return ;;"
    ) ++ arms ++ List(
      "    *) COMPREPLY=(); return ;;",
      "  esac",
      "",
      "  if [[ $cur == -* ]]; then",
      "    COMPREPLY=( $(compgen -W \"$opts --help\" -- \"$cur\") ); return",
      "  fi",
      "",
      "  # Index of the current positional (0 = first), skipping flags and the value a value-flag consumes.",
      "  local posn=0 j skip=0 w base=1",
      "  for (( j = 1; j < cword; j++ )); do",
      "    w=\"${words[j]}\"",
      "    if (( skip )); then skip=0; continue; fi",
      "    case \"$w\" in",
      "      -*) case \"$w\" in " + valueGuard + ") skip=1 ;; esac ;;",
      "      *) (( posn++ )) ;;",
      "    esac",
      "  done",
      "  [[ " + groupBaseGuard + " ]] && base=2",
      "  local posIndex=$(( posn - base ))",
      "",
      "  case \"$pos\" in",
      "    slugs) COMPREPLY=( $(compgen -W \"$(_ccas_cache clubs.txt)\" -- \"$cur\") ) ;;",
      "    slug)  (( posIndex == 0 )) && COMPREPLY=( $(compgen -W \"$(_ccas_cache clubs.txt)\" -- \"$cur\") ) ;;",
      "    jobid) (( posIndex == 0 )) && COMPREPLY=( $(compgen -W \"$(_ccas_cache recent-jobs.txt)\" -- \"$cur\") ) ;;",
      "    shell) (( posIndex == 0 )) && COMPREPLY=( $(compgen -W \"bash zsh fish\" -- \"$cur\") ) ;;",
      "    *) COMPREPLY=( $(compgen -W \"$opts --help\" -- \"$cur\") ) ;;",
      "  esac",
      "}",
      "complete -F _ccas ccas"
    )
    lines.mkString("\n") + "\n"
  }

  // --- zsh ---

  private def zshLeafArm(leaf: Leaf): String =
    "    " + leaf.name + ") " + assigns(leaf) + " ;;"

  private def zshGroupArm(group: Group): String = {
    val header = List(
      "    " + group.name + ")",
      "      case \"$sub\" in",
      "        \"\") compadd -- " + group.children.mkString(" ") + " --help; return ;;"
    )
    val childArms = CompletionSpec.leavesOf(group.name).map(l => "        " + l.name + ") " + assigns(l) + " ;;")
    val footer = List("        *) return ;;", "      esac ;;")
    (header ++ childArms ++ footer).mkString("\n")
  }

  val zsh: String = {
    val arms = CompletionSpec.topLevel.flatMap { name =>
      CompletionSpec.groups.find(_.name == name).map(zshGroupArm)
        .orElse(CompletionSpec.topLevelLeaves.find(_.name == name).map(zshLeafArm))
    }
    val lines = List(
      "# zsh completion for ccas — generated, pure-shell (JVM-free). See Sootopolis/ccas#49.",
      "# Enable:  eval \"$(ccas completion zsh)\"   (add to ~/.zshrc, after `autoload -Uz compinit && compinit`).",
      "",
      "_ccas_cache() {",
      "  local f=\"${XDG_CACHE_HOME:-$HOME/.cache}/ccas/$1\"",
      "  [[ -r $f ]] && cat -- \"$f\"",
      "}",
      "",
      "_ccas() {",
      "  local top=\"" + top + "\"",
      "  local global=\"" + global + "\"",
      "  local cur=\"${words[CURRENT]}\" prev=\"${words[CURRENT-1]}\"",
      "",
      "  local cmd=\"\" sub=\"\" i",
      "  for (( i = 2; i < CURRENT; i++ )); do",
      "    case \"${words[i]}\" in",
      "      -*) ;;",
      "      *) if [[ -z $cmd ]]; then cmd=\"${words[i]}\"; else sub=\"${words[i]}\"; break; fi ;;",
      "    esac",
      "  done",
      "",
      "  case \"$prev\" in",
      "    " + valueGuard + ") return ;;",
      "  esac",
      "",
      "  local opts=\"\" pos=\"\"",
      "  case \"$cmd\" in",
      "    \"\") compadd -- ${=top} ${=global}; return ;;"
    ) ++ arms ++ List(
      "    *) return ;;",
      "  esac",
      "",
      "  if [[ $cur == -* ]]; then compadd -- ${=opts} --help; return; fi",
      "",
      "  local posn=0 j skip=0 w base=1",
      "  for (( j = 2; j < CURRENT; j++ )); do",
      "    w=\"${words[j]}\"",
      "    if (( skip )); then skip=0; continue; fi",
      "    case \"$w\" in",
      "      -*) case \"$w\" in " + valueGuard + ") skip=1 ;; esac ;;",
      "      *) (( posn++ )) ;;",
      "    esac",
      "  done",
      "  [[ " + groupBaseGuard + " ]] && base=2",
      "  local posIndex=$(( posn - base ))",
      "",
      "  case \"$pos\" in",
      "    slugs) compadd -- ${(f)\"$(_ccas_cache clubs.txt)\"} ;;",
      "    slug)  (( posIndex == 0 )) && compadd -- ${(f)\"$(_ccas_cache clubs.txt)\"} ;;",
      "    jobid) (( posIndex == 0 )) && compadd -- ${(f)\"$(_ccas_cache recent-jobs.txt)\"} ;;",
      "    shell) (( posIndex == 0 )) && compadd -- bash zsh fish ;;",
      "    *) compadd -- ${=opts} --help ;;",
      "  esac",
      "}",
      "",
      "compdef _ccas ccas 2>/dev/null"
    )
    lines.mkString("\n") + "\n"
  }

  // --- fish ---

  private def fishLong(flag: String): String = flag.stripPrefix("--")

  private def fishCond(leaf: Leaf): String = leaf.path match {
    case g :: c :: Nil => "__fish_seen_subcommand_from " + g + "; and __fish_seen_subcommand_from " + c
    case name :: Nil   => "__fish_seen_subcommand_from " + name
    case _             => ""
  }

  private def fishFlagLines(leaf: Leaf): List[String] = {
    val cond = fishCond(leaf)
    // `--help` is on every command (zio-cli built-in); append it for parity with the bash/zsh scripts.
    (leaf.flags :+ "--help").distinct.map { f =>
      val rArg = if (leaf.valueFlags.contains(f)) " -r" else ""
      "complete -c ccas -n '" + cond + "' -l " + fishLong(f) + rArg
    }
  }

  // NOTE: unlike the bash/zsh scripts (which track a positional index), fish offers club slugs at *every* positional of
  // a single-slug command, not just the first — fish has no portable positional-count primitive, and the over-suggestion
  // is cosmetic (e.g. `blacklist remove <slug> <username>` briefly offers slugs at the username). Slugs/JobId/Shell are
  // all cache-or-static candidates fish filters by the typed prefix, so a stray suggestion is harmless.
  private def fishPosLine(leaf: Leaf): Option[String] = {
    val cond = fishCond(leaf)
    val cache = leaf.positional match {
      case PositionalKind.Slugs | PositionalKind.Slug => Some("(__fish_ccas_cache clubs.txt)")
      case PositionalKind.JobId                       => Some("(__fish_ccas_cache recent-jobs.txt)")
      case PositionalKind.Shell                       => Some("bash zsh fish")
      case _                                          => None
    }
    cache.map(a => "complete -c ccas -n '" + cond + "' -f -a '" + a + "'")
  }

  val fish: String = {
    val header = List(
      "# fish completion for ccas — generated, pure-shell (JVM-free). See Sootopolis/ccas#49.",
      "# Install:  ccas completion fish > ~/.config/fish/completions/ccas.fish",
      "",
      "function __fish_ccas_cache",
      "  set -l base \"$XDG_CACHE_HOME\"",
      "  test -z \"$base\"; and set base \"$HOME/.cache\"",
      "  set -l f \"$base/ccas/$argv[1]\"",
      "  test -r \"$f\"; and cat -- \"$f\"",
      "end",
      "",
      "complete -c ccas -f"
    )
    // Top-level subcommands (only before any subcommand is chosen).
    val topSubs = CompletionSpec.topLevel.map { name =>
      val summary = CompletionSpec.groups.find(_.name == name).map(_.summary)
        .orElse(CompletionSpec.topLevelLeaves.find(_.name == name).map(_.summary))
        .getOrElse("")
      "complete -c ccas -n '__fish_use_subcommand' -a '" + name + "' -d \"" + summary + "\""
    }
    // Group children (e.g. blacklist add/list/remove), shown once the group is seen but no child is.
    val groupChildren = CompletionSpec.groups.flatMap { g =>
      val notAny = "; and not __fish_seen_subcommand_from " + g.children.mkString(" ")
      CompletionSpec.leavesOf(g.name).map { l =>
        "complete -c ccas -n '__fish_seen_subcommand_from " + g.name + notAny + "' -a '" + l.name +
          "' -d \"" + l.summary + "\""
      }
    }
    val flagLines = CompletionSpec.leaves.flatMap(fishFlagLines) ++
      List("complete -c ccas -n '__fish_use_subcommand' -l version")
    val posLines = CompletionSpec.leaves.flatMap(fishPosLine)
    (header ++ List("") ++ topSubs ++ List("") ++ groupChildren ++ List("") ++ flagLines ++ List("") ++ posLines)
      .mkString("\n") + "\n"
  }
}
