# bash completion for ccas — generated, pure-shell (JVM-free, instant). See Sootopolis/ccas#49.
#
# DO NOT EDIT — generated by `ccas completion bash`.
# Regenerate after a command-tree change:  ccas completion bash > completions/ccas.bash
# TestCcasCompletion asserts this file equals the emitter output and stays valid bash.
#
# Install:  ln -sf "$PWD/completions/ccas.bash" ~/.local/share/bash-completion/completions/ccas
# (bash-completion auto-loads it; or `source` it from ~/.bashrc).
#
# Club-slug and job-id completion read caches refreshed by normal ccas commands:
#   ${XDG_CACHE_HOME:-$HOME/.cache}/ccas/clubs.txt        (one slug per line)
#   ${XDG_CACHE_HOME:-$HOME/.cache}/ccas/recent-jobs.txt  (one job id per line)
#
# COMPREPLY=( $(compgen ...) ) is the standard, bash-3.2/macOS-safe completion idiom; the word-splitting is
# intentional (compgen yields newline-separated, space-free candidates). mapfile is the SC2207 fix but is bash 4+.
# shellcheck disable=SC2207

_ccas_cache() {
  local f="${XDG_CACHE_HOME:-$HOME/.cache}/ccas/$1"
  [[ -r $f ]] && cat -- "$f"
}

_ccas() {
  local cur prev words cword
  if declare -F _init_completion >/dev/null 2>&1; then
    _init_completion -n : || return
  else
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cword=$COMP_CWORD
    words=("${COMP_WORDS[@]}")
  fi

  local top="server use-club membership history recruit stats jobs logs cancel blacklist schedule club config completion"
  local global="--help --version"
  local envkeys="CCAS_CONTACT_EMAIL DATABASE_URL DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD DB_SCHEMA SERVER_PORT SERVER_HOST JOB_LOGS_DIR SCHEDULER_POLL_MINUTES SCHEDULER_MATCHREF_INTERVAL_HOURS SCHEDULER_MATCHREF_ENABLED SCHEDULER_CLUBDATA_INTERVAL_HOURS SCHEDULER_CLUBDATA_ENABLED SCHEDULER_HISTORY_INTERVAL_HOURS SCHEDULER_HISTORY_ENABLED SCHEDULER_MEMBERSHIP_INTERVAL_HOURS SCHEDULER_MEMBERSHIP_ENABLED DB_POOL_MAX DB_POOL_MIN_IDLE DB_POOL_CONNECTION_TIMEOUT DB_POOL_IDLE_TIMEOUT DB_POOL_MAX_LIFETIME DB_POOL_KEEPALIVE_TIME DB_POOL_CONNECTION_TEST_QUERY DB_POOL_INIT_FAIL_TIMEOUT DB_SOCKET_TIMEOUT_SECONDS DB_CONNECT_TIMEOUT_SECONDS DB_TCP_KEEP_ALIVE DB_RETRY_BASE_DELAY_MS DB_RETRY_MAX_RETRIES CHESS_COM_API_RECOVERY_TIERS CHESS_COM_API_COOLDOWN_SECONDS CHESS_COM_API_CF_COOLDOWN_SECONDS CHESS_COM_API_FAILURE_WINDOW_SIZE CHESS_COM_API_FAILURE_THRESHOLD CHESS_COM_API_MIN_SAMPLE_SIZE CHESS_COM_API_MIN_REQUEST_DELAY_MS CHESS_COM_API_EMA_TAU_MS CHESS_COM_API_MIN_TIER_OBSERVATION_SECONDS CHESS_COM_API_RETRY_BASE_SECONDS CHESS_COM_API_CF_RETRY_DELAY_SECONDS CHESS_COM_API_CONNECTION_RETRY_BASE_SECONDS CHESS_COM_API_MAX_429_RETRIES CHESS_COM_API_MAX_CF_RETRIES CHESS_COM_API_MAX_CONNECTION_RETRIES CHESS_COM_API_STATS_FLUSH_INTERVAL_SECONDS"

  # First non-flag word after "ccas" is the command; the next is the subcommand (server/blacklist/schedule/club/config).
  local cmd="" sub="" i
  for (( i = 1; i < cword; i++ )); do
    case "${words[i]}" in
      -*) ;;
      *) if [[ -z $cmd ]]; then cmd="${words[i]}"; else sub="${words[i]}"; break; fi ;;
    esac
  done

  # Right after --club: offer cached club slugs. Right after any other value flag: offer nothing.
  case "$prev" in
    --club) COMPREPLY=( $(compgen -W "$(_ccas_cache clubs.txt)" -- "$cur") ); return ;;
    --server|--club|--refresh-min-hours|--alias|--target|--source-clubs|--time-limit-minutes|--since|--until|--limit|--reason|--months|--kind|--interval-hours|--cron|--tz|--misfire|--params) return ;;
  esac

  local opts="" pos=""
  case "$cmd" in
    "") COMPREPLY=( $(compgen -W "$top $global" -- "$cur") ); return ;;
    server)
      case "$sub" in
        "") COMPREPLY=( $(compgen -W "up down status --help" -- "$cur") ); return ;;
        up) opts="--detach -d" ;;
        down)  ;;
        status)  ;;
        *) COMPREPLY=(); return ;;
      esac ;;
    use-club) pos="slug" ;;
    membership) opts="--server --trust-usernames --no-trust-usernames --club --all --no-progress" ;;
    history) opts="--server --full --include-finished --refresh --refresh-min-hours --club --all --no-progress" ;;
    recruit) opts="--server --alias --target --cumulative --source-clubs --time-limit-minutes --explore --no-explore --club --stdout --report --no-progress" ;;
    stats) opts="--server --since --until --club --no-progress" ;;
    jobs) opts="--server --limit" ;;
    logs) opts="--server --no-progress"; pos="jobid" ;;
    cancel) opts="--server"; pos="jobid" ;;
    blacklist)
      case "$sub" in
        "") COMPREPLY=( $(compgen -W "add list remove --help" -- "$cur") ); return ;;
        add) opts="--server --reason --months --club" ;;
        list) opts="--server --club" ;;
        remove) opts="--server --club" ;;
        *) COMPREPLY=(); return ;;
      esac ;;
    schedule)
      case "$sub" in
        "") COMPREPLY=( $(compgen -W "list add remove --help" -- "$cur") ); return ;;
        list) opts="--server" ;;
        add) opts="--server --kind --interval-hours --cron --tz --misfire --club --params" ;;
        remove) opts="--server" ;;
        *) COMPREPLY=(); return ;;
      esac ;;
    club)
      case "$sub" in
        "") COMPREPLY=( $(compgen -W "add remove list --help" -- "$cur") ); return ;;
        add) opts="--server"; pos="slug" ;;
        remove) opts="--server"; pos="slug" ;;
        list) opts="--server" ;;
        *) COMPREPLY=(); return ;;
      esac ;;
    config)
      case "$sub" in
        "") COMPREPLY=( $(compgen -W "get set unset list show path init --help" -- "$cur") ); return ;;
        get) pos="envkey" ;;
        set) pos="envkey" ;;
        unset) pos="envkey" ;;
        list) opts="--show-secrets" ;;
        show) opts="--show-secrets" ;;
        path)  ;;
        init)  ;;
        *) COMPREPLY=(); return ;;
      esac ;;
    completion) pos="shell" ;;
    *) COMPREPLY=(); return ;;
  esac

  if [[ $cur == -* ]]; then
    COMPREPLY=( $(compgen -W "$opts --help" -- "$cur") ); return
  fi

  # Index of the current positional (0 = first), skipping flags and the value a value-flag consumes.
  local posn=0 j skip=0 w base=1
  for (( j = 1; j < cword; j++ )); do
    w="${words[j]}"
    if (( skip )); then skip=0; continue; fi
    case "$w" in
      -*) case "$w" in --server|--club|--refresh-min-hours|--alias|--target|--source-clubs|--time-limit-minutes|--since|--until|--limit|--reason|--months|--kind|--interval-hours|--cron|--tz|--misfire|--params) skip=1 ;; esac ;;
      *) (( posn++ )) ;;
    esac
  done
  [[ $cmd == server || $cmd == blacklist || $cmd == schedule || $cmd == club || $cmd == config ]] && base=2
  local posIndex=$(( posn - base ))

  case "$pos" in
    slug)   (( posIndex == 0 )) && COMPREPLY=( $(compgen -W "$(_ccas_cache clubs.txt)" -- "$cur") ) ;;
    jobid)  (( posIndex == 0 )) && COMPREPLY=( $(compgen -W "$(_ccas_cache recent-jobs.txt)" -- "$cur") ) ;;
    shell)  (( posIndex == 0 )) && COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ) ;;
    envkey) (( posIndex == 0 )) && COMPREPLY=( $(compgen -W "$envkeys" -- "$cur") ) ;;
    *) COMPREPLY=( $(compgen -W "$opts --help" -- "$cur") ) ;;
  esac
}
complete -F _ccas ccas
