# bash completion for ccas — generated, pure-shell (JVM-free, instant). See Sootopolis/ccas#49.
#
# DO NOT EDIT — generated by `ccas completion bash`.
# Regenerate after a command-tree change:  ccas completion bash > completions/ccas.bash
# TestCcasCompletion asserts this file equals the emitter output and stays valid bash.
#
# Install:  ln -sf "$PWD/completions/ccas.bash" ~/.local/share/bash-completion/completions/ccas
# (bash-completion auto-loads it; or `source` it from ~/.bashrc).
#
# Club-slug and job-id completion read caches refreshed by normal ccas commands:
#   ${XDG_CACHE_HOME:-$HOME/.cache}/ccas/clubs.txt        (one slug per line)
#   ${XDG_CACHE_HOME:-$HOME/.cache}/ccas/recent-jobs.txt  (one job id per line)

_ccas_cache() {
  local f="${XDG_CACHE_HOME:-$HOME/.cache}/ccas/$1"
  [[ -r $f ]] && cat -- "$f"
}

_ccas() {
  local cur prev words cword
  if declare -F _init_completion >/dev/null 2>&1; then
    _init_completion -n : || return
  else
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cword=$COMP_CWORD
    words=("${COMP_WORDS[@]}")
  fi

  local top="serve membership history recruit stats jobs logs blacklist schedule completion"
  local global="--help --version"

  # First non-flag word after "ccas" is the command; the next is the subcommand (blacklist/schedule).
  local cmd="" sub="" i
  for (( i = 1; i < cword; i++ )); do
    case "${words[i]}" in
      -*) ;;
      *) if [[ -z $cmd ]]; then cmd="${words[i]}"; else sub="${words[i]}"; break; fi ;;
    esac
  done

  # Right after a value-taking flag: let the user type the value, offer nothing.
  case "$prev" in
    --server|--refresh-min-hours|--alias|--target|--source-clubs|--time-limit-minutes|--since|--until|--limit|--reason|--months|--kind|--interval-hours|--club|--params) return ;;
  esac

  local opts="" pos=""
  case "$cmd" in
    "") COMPREPLY=( $(compgen -W "$top $global" -- "$cur") ); return ;;
    serve) opts="--server" ;;
    membership) opts="--server --trust-usernames --no-trust-usernames"; pos="slugs" ;;
    history) opts="--server --full --include-finished --refresh --refresh-min-hours"; pos="slugs" ;;
    recruit) opts="--server --alias --target --cumulative --source-clubs --time-limit-minutes --explore --no-explore"; pos="slug" ;;
    stats) opts="--server --since --until"; pos="slug" ;;
    jobs) opts="--server --limit" ;;
    logs) opts="--server"; pos="jobid" ;;
    blacklist)
      case "$sub" in
        "") COMPREPLY=( $(compgen -W "add list remove --help" -- "$cur") ); return ;;
        add) opts="--server --reason --months"; pos="slug" ;;
        list) opts="--server"; pos="slug" ;;
        remove) opts="--server"; pos="slug" ;;
        *) COMPREPLY=(); return ;;
      esac ;;
    schedule)
      case "$sub" in
        "") COMPREPLY=( $(compgen -W "list add remove --help" -- "$cur") ); return ;;
        list) opts="--server" ;;
        add) opts="--server --kind --interval-hours --club --params" ;;
        remove) opts="--server" ;;
        *) COMPREPLY=(); return ;;
      esac ;;
    completion) pos="shell" ;;
    *) COMPREPLY=(); return ;;
  esac

  if [[ $cur == -* ]]; then
    COMPREPLY=( $(compgen -W "$opts --help" -- "$cur") ); return
  fi

  # Index of the current positional (0 = first), skipping flags and the value a value-flag consumes.
  local posn=0 j skip=0 w base=1
  for (( j = 1; j < cword; j++ )); do
    w="${words[j]}"
    if (( skip )); then skip=0; continue; fi
    case "$w" in
      -*) case "$w" in --server|--refresh-min-hours|--alias|--target|--source-clubs|--time-limit-minutes|--since|--until|--limit|--reason|--months|--kind|--interval-hours|--club|--params) skip=1 ;; esac ;;
      *) (( posn++ )) ;;
    esac
  done
  [[ $cmd == blacklist || $cmd == schedule ]] && base=2
  local posIndex=$(( posn - base ))

  case "$pos" in
    slugs) COMPREPLY=( $(compgen -W "$(_ccas_cache clubs.txt)" -- "$cur") ) ;;
    slug)  (( posIndex == 0 )) && COMPREPLY=( $(compgen -W "$(_ccas_cache clubs.txt)" -- "$cur") ) ;;
    jobid) (( posIndex == 0 )) && COMPREPLY=( $(compgen -W "$(_ccas_cache recent-jobs.txt)" -- "$cur") ) ;;
    shell) (( posIndex == 0 )) && COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ) ;;
    *) COMPREPLY=( $(compgen -W "$opts --help" -- "$cur") ) ;;
  esac
}
complete -F _ccas ccas
